# Site settings
title: blackwilmar in the Hour of Chaos
email: wilmars@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  It puts the value in its array.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blackwilmar.github.io" # the base hostname & protocol for your site
twitter_username: blackwilmar
github_username:  blackwilmar

# Build settings
markdown: kramdown
